spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/db_elearning_a1_m1
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 111999
  application:
    name: elearning-a01-m1


server:
  port: 8081