spring:
  application:
    name: elearning-a01-m1

  datasource:
    url: jdbc:postgresql://localhost:5432/db_elearning_a1_m1
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 111999

  jpa:
    hibernate:
      ddl-auto: update


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/elearning

server:
  port: 8081

#  http://localhost:8080/realms/master
keycloak:
  server-url:  http://localhost:8080
  client-id: spring-boot-elearning
  client-secret: giXU1q5B8F5nuwAP9cSpdklQhMRAqyA0
  realm: master
  target-realm: elearning


